### ISSUE TITLE
how to make a GTF file for HTSeq-Transcriptome

### ISSUE THREAD

**Issue by faguil** [oxpeter/htseq-transcriptome#2]
Hi, 

I would like to use htseq-transcriptome on some bam files that were generated using RSEM with a de novo transcriptome as a reference. Therefore, I don't have a GTF file. So, I am wondering how to run htseq-transcriptome without having a GTF file or I have to provide one. If the second option should be done, how can I create a GTF file from a de novo reference transcriptome.

Hope someone else can help me with this matter.

Thanks in advance,

Felipe

**Comment by faguil** [comment]
If someone is interested in how to create a fake GFT file for using htseq-transcriptome, I did the following and it worked.

$ faSize -detailed transcriptome.fa > transcriptome.sizes.txt
$ cat transcripome.sizes.txt | awk '{print $1"\tGene\texon\t1\t"$2"\t\.\t\+\t.\tgene_id \""$1"\""}' >> transcriptome.gtf

**Comment by faguil** [comment]
But now I am having this error at the counting reads steps
Counting reads...
Traceback (most recent call last):
  File "/usr/local/src/htseq-transcriptome-master/htseq-trancriptome.py", line 219, in <module>
    counts = ungapped_se_counter(alnmt_file, feature_array)
  File "/usr/local/src/htseq-transcriptome-master/htseq-trancriptome.py", line 51, in ungapped_se_counter
    count[ "_unmapped" ] += 1
NameError: global name 'count' is not defined

Any helps to solve this issue is super welcome.

Thanks in advance,

Felipe

**Comment by oxpeter** [comment]
How was the transciptome assembled? Programs like Trinity can output a GTF file even for transcriptomes. More importantly, do you have any prediction/information regarding which isoforms belong to which genes? HTSeq-transcriptome has been adapted from HTSeq to allow accounting for reads that will map to multiple transcripts, because these are isoforms of the same gene. If you do not have information that places isoforms together into genes, then you can run the standard HTSeq program, treating each isoform as a separate gene (but know that you will lose many of your reads, as the different isoforms will instead be interpreted as being multiply mapped)

**Comment by oxpeter** [comment]
@faguil, your error described above was caused by a bug that made SE read alignment fail for unmapped reads in bam files. This has been corrected now, so you should be able to run things without incident.

**Comment by faguil** [comment]
Hi Oxpeter,

Thanks for fixing this bug, I ran a couple of SAM files, along with my fake GTF file, and everything worked smoothly. 

I have also tested mmquant and both (mmquant and htseq-transcriptome) gave me the same results. So, I think everything is ok.

Thanks again,

**Comment by oxpeter** [comment]
Awesome, thanks for the testing!
